---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.name }}-cli
  namespace: {{ .Release.Namespace }}
{{- if .Values.cli.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.cli.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  CNS_HOST: "{{ .Values.name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local"
  CNS_PORT: "2379"
  CNS_PROFILES: "https://cp.padi.io/profiles"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-cli
  labels:
    name: {{ .Values.name }}-cli
spec:
  replicas: {{ .Values.cli.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-cli
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-cli
      annotations:
        {{ if .Values.cli.rollPods }}
        rollme: {{ randAlphaNum 5 | quote }} 
        {{ end }}
    spec:
      serviceAccountName: {{ .Values.name }}-cli
      {{- if .Values.cli.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.cli.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}-cli
          image: {{ .Values.cli.imageRepository }}:{{ .Values.cli.imageTag }}
          {{- if .Values.cli.command }}
          command: {{ .Values.cli.command | toJson }}
          {{- end }}
          imagePullPolicy: {{ .Values.cli.pullPolicy }}
          env:
          {{- if .Values.cli.env }}
          {{- range .Values.cli.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
            - name: CNS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "arete.user.etcdSecretName" . }}
                  key: CNS_USERNAME
            - name: CNS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "arete.user.etcdSecretName" . }}
                  key: CNS_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-config
          ports:
            - containerPort: {{ .Values.cli.dashboardPort }}
          resources:
            requests:
              cpu: {{ .Values.cli.requests.cpu }}
              memory: {{ .Values.cli.requests.memory }}
            limits:
              cpu: {{ .Values.cli.limits.cpu }}
              memory: {{ .Values.cli.limits.memory }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}-cli
  ports:
    - port: {{ .Values.cli.dashboardPort }}

---
{{- if .Values.cli.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: {{ .Values.name }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.name }}.aretehosting.com`)
    services:
    - name: {{ .Values.name }}-dashboard
      port: {{ .Values.cli.dashboardPort }}
  tls:
    secretName: arete-hosting-tls
{{- end }}