---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-etcd
  labels:
    app: {{ .Values.name }}-etcd
spec:
  ports:
  - port: {{ .Values.etcd.servicePort }}
    targetPort: {{ .Values.etcd.servicePort }}
    name: "{{ .Values.name }}-client"
  - port: {{ .Values.etcd.peerPort }}
    targetPort: {{ .Values.etcd.peerPort }}
    name: "{{ .Values.name }}-peer"
  selector:
    app: {{ .Values.name }}-etcd
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-cli
spec:
  selector:
    app: {{ .Values.name }}-cli
  ports:
    - protocol: TCP
      port: {{ .Values.cli.servicePort }}
      targetPort: {{ .Values.cli.containerPort }}

