# required
# name:

cli:
  serviceAccountName: cli
  imageRepository: us-central1-docker.pkg.dev/padi-staging/cnscp/cns-cli
  imageTag: latest
  pullPolicy: Always
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'


etcd:
  imageRepository: quay.io/coreos/etcd
  replicas: 1
  imageTag: 'v3.5.0'
  servicePort: 2379
  peerPort: 2380
  args:
    - arg: "name"
      value: "arete-etcd-0"
    - arg: "listen-client-urls"
      value: "http://0.0.0.0:2379"
    - arg: "advertise-client-urls"
      value: "http://0.0.0.0:2379"
    # - arg: "data-dir"
    #   value: "/etcd-data"
  dataMountPoint: "/etcd-data"
  env:
    # - name: foo
    #   value: bar
  pvc:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    volumeSize: 1Gi
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'
  ingress:
    enabled: true


orch:
  imageRepository: us-central1-docker.pkg.dev/padi-staging/cnscp/cns-orchestrator
  imageTag: latest
  pullPolicy: Always
  replicas: 1
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'
