# required
# name:

arete:
  # Name of the k8s secret containing the CNS_USERNAME and CNS_PASSWORD
  # Defaults to <name>-etcd-user
  credentialsSecretRef: ""

cli:
  serviceAccountName: cli
  imagePullSecrets:
    - padi-artifact-hub
  imageRepository: us-central1-docker.pkg.dev/padi-80910/cnscp-preprod/cns-cli
  imageTag: staging
  pullPolicy: Always
  replicas: 1
  env:
    - name: DEBUG
      value: true
  dashboardPort: 8080
  networkPort: 2379
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'
  ingress:
    enabled: true


etcd:
  imageRepository: quay.io/coreos/etcd
  replicas: 1
  imageTag: 'v3.5.0'
  servicePort: 2379
  peerPort: 2380
  configureUsers: true
  # username: "<AUTO_GENERATED>"
  # password: <AUTO_GENERATED>
  args:
    - arg: "name"
      value: "arete-etcd-0"
    - arg: "listen-client-urls"
      value: "http://0.0.0.0:2379"
    - arg: "advertise-client-urls"
      value: "http://0.0.0.0:2379"
    - arg: "data-dir"
      value: "/etcd-data"
  dataMountPoint: "/etcd-data"
  env:
    # - name: foo
    #   value: bar
  pvc:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    volumeSize: 1Gi
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'
  ingress:
    enabled: false


orch:
  imagePullSecrets:
    - padi-artifact-hub
  imageRepository: us-central1-docker.pkg.dev/padi-80910/cnscp-preprod/cns-orchestrator
  imageTag: staging
  pullPolicy: Always
  env:
    # - name: foo
    #   value: bar
  replicas: 1
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'
